site_name: Synthetic
site_url: https://synthetic-models.github.io/
theme:
  name: material
  palette:
    primary: indigo
plugins:
  - mkdocstrings
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Network & Drug Design: network_and_drug_design.md
  - Solvers & Simulation: solvers_and_simulation.md
  - Data Generation: data_generation.md
  - Advanced Workflows: advanced_workflows.md